export const APP_INIT = 'APP_INIT';

export const SAVE_STROKE_LOCATION_DATA = 'SAVE_STROKE_LOCATION_DATA';

export const ADD_COURSE = 'ADD_COURSE';
export const ADD_CLUB = 'ADD_CLUB';

export const ADD_CLUB_TO_BAG = 'ADD_CLUB_TO_BAG';
export const REMOVE_CLUB_FROM_BAG = 'REMOVE_CLUB_FROM_BAG';
